pkgconfig: Add Cflags.private field for static linking
This defines LIBJASPER_STATIC_DEFINE when static linking is expected.
The Cflags.private field depends on pkgconf rather than pkg-config.
Without this change, linker finds exported APIs with dllimport and
it produces the error:

ld.exe: test_1.c:(.text+0x2b): undefined reference to `__imp_jas_get_total_mem_size'
ld.exe: test_1.c:(.text+0x4b): undefined reference to `__imp_jas_optarg'
and more.

Result of this change:

* Before:
$ pkgconf -cflags -static jasper
-IF:/msys64/ucrt64/include/jasper -IF:/msys64/ucrt64/include

* After:
$ pkgconf -cflags -static jasper
-IF:/msys64/ucrt64/include/jasper -IF:/msys64/ucrt64/include -DLIBJASPER_STATIC_DEFINE